version: '3.7'

services:
  simpleproject.api:
    build:
      context: .
      dockerfile: SimpleProject.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - DB_CONNECTION_STRING=host=postgres;port=5432;database=simpleprojectdb;username=simpleprojectuser;password=strongpassword2
    networks:
      - simpleproject
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=simpleprojectuser
      - POSTGRES_PASSWORD=strongpassword2
      - POSTGRES_DB=simpleprojectdb
    networks:
      - simpleproject
      
networks:
  simpleproject:
    driver: bridge

volumes:
  db-data:
    driver: local