version: '3.7'

services:
  simpleproject.api:
    build:
      context: .
      dockerfile: SimpleProject.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - DB_CONNECTION_STRING=host=postgres;port=5432;database=simpleprojectdb;username=simpleprojectuser;password=strongpassword2
    networks:
      - simpleproject
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=simpleprojectuser
      - POSTGRES_PASSWORD=strongpassword2
      - POSTGRES_DB=simpleprojectdb
      - PG_SYSTEM_SHARED_BUFFERS=6000MB
      - PG_SYSTEM_MAX_CONNECTIONS=2000
    command: ["-c", "shared_buffers=6000MB", "-c", "max_connections=2000"]
    networks:
      - simpleproject

  simpleproject.gateway:
    build:
      context: .
      dockerfile: SimpleProject.Gateway/Dockerfile
    ports:
      - "5050:80"
    environment:
      - SIMPLE_API_URL=http://simpleproject.api/
    networks:
      - simpleproject
    depends_on:
      - simpleproject.api

networks:
  simpleproject:
    driver: bridge

volumes:
  db-data:
    driver: local